#!/usr/bin/env bash
# Write a script that displays "Best School" 10 times, but on 9th iteration, display "Best school" and then "Hi" on a new line

i=0

while [ $i -ne 10 ]
    do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( i++ ))
done
