#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

HOUR=0
MINUTE=1

while [[ $HOUR -le 12 ]]
do
    echo "Hour: $HOUR"
    while [[ $MINUTE -ne 60 ]]
    do
        echo "$MINUTE"
        (( MINUTE++ ))
    done
    MINUTE=1
    (( HOUR++ ))
done
